# Generated by Django 2.2.2 on 2021-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_sukashi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sukashi',
            name='splace',
            field=models.CharField(default='yokohama', max_length=40, verbose_name='採取地'),
            preserve_default=False,
        ),
    ]
