# Generated by Django 2.2.2 on 2021-09-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_remove_sukashi_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sukashi',
            name='rare',
            field=models.IntegerField(choices=[(1, '1\u3000どこにでもある'), (2, '2\u3000ちょっと探せばある'), (3, '3\u3000ちょっと探してもない'), (4, '4\u3000かなり探すとある'), (5, '5\u3000奇跡の出会い')], default=3, verbose_name='レアレベル'),
            preserve_default=False,
        ),
    ]
