# Generated by Django 2.2.2 on 2021-09-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20210918_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='sukashi',
            name='oflag',
            field=models.IntegerField(choices=[(1, '公開'), (2, '限定公開'), (3, '非公開')], default=1, verbose_name='公開フラグ'),
        ),
    ]
