# Generated by Django 3.2.7 on 2022-11-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_good'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='sukashi_id',
            new_name='sukashi',
        ),
    ]
